/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PerBerasan;

import java.awt.HeadlessException;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author LEGION
 */
public class GUDANG extends javax.swing.JFrame {
    private void kosongkan(){
        txtKode.setEditable(true);
        txtKode.setText(null);
        txtMerk.setText(null);
        txtStok.setText(null);
    }
    private void tampilkan(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No. ");
        model.addColumn("Merk Beras");
        model.addColumn("Kode Beras");
        model.addColumn("Stok Beras");
        
        try{
            int no = 1;
            String sql = "SELECT * FROM gudang";
            java.sql.Connection conn = (Connection)tokoberas.configDB();
            java.sql.Statement sta = conn.createStatement();
            java.sql.ResultSet res = sta.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3)});
     
            }
            tabelGudang.setModel(model);
            
        }catch(SQLException e){
            System.out.println("ERROR !"+e.getMessage());
        }
        
    }
    
   
    public GUDANG() {
        initComponents();
        tampilkan();
        kosongkan();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        txtMerk = new javax.swing.JTextField();
        txtStok = new javax.swing.JTextField();
        tbHapus = new javax.swing.JButton();
        tbOut = new javax.swing.JButton();
        tbSave = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelGudang = new javax.swing.JTable();
        tbEdit = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("GUDANG BERAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 10, -1, 28));

        jLabel2.setText("Kode Beras");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel3.setText("Merk Beras");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel4.setText("Stok Beras");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 80, -1));
        getContentPane().add(txtKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 211, -1));
        getContentPane().add(txtMerk, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 211, -1));
        getContentPane().add(txtStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 211, -1));

        tbHapus.setText("Hapus");
        tbHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbHapusActionPerformed(evt);
            }
        });
        getContentPane().add(tbHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        tbOut.setForeground(new java.awt.Color(255, 51, 0));
        tbOut.setText("X");
        tbOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbOutActionPerformed(evt);
            }
        });
        getContentPane().add(tbOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        tbSave.setText("Simpan");
        tbSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSaveActionPerformed(evt);
            }
        });
        getContentPane().add(tbSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        tabelGudang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelGudang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelGudangMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabelGudang);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 360, 150));

        tbEdit.setText("Edit Data");
        tbEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbEditActionPerformed(evt);
            }
        });
        getContentPane().add(tbEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbOutActionPerformed
            System.exit(0);
    }//GEN-LAST:event_tbOutActionPerformed

    private void tbSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSaveActionPerformed
        try{
            String sql = "INSERT INTO gudang VALUES ('"+txtMerk.getText()+"','"+txtKode.getText()+"','"+txtStok.getText()+"')";
            java.sql.Connection conn =  (Connection)tokoberas.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            tampilkan();
            kosongkan();
            
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_tbSaveActionPerformed

    private void tabelGudangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelGudangMouseClicked
        int baris = tabelGudang.rowAtPoint (evt.getPoint());
        String merk = tabelGudang.getValueAt(baris, 1).toString();
        txtMerk.setText(merk);
        String kode = tabelGudang.getValueAt(baris, 2).toString();
        txtKode.setText(kode);
        String stok = tabelGudang.getValueAt(baris, 3).toString();
        txtStok.setText(stok);

    }//GEN-LAST:event_tabelGudangMouseClicked

    private void tbEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbEditActionPerformed
        try{
            String sql = "UPDATE gudang SET merk_beras='"+txtMerk.getText()+"',kode_beras='"+txtKode.getText()+"',stok='"+txtStok.getText()+"' WHERE merk_beras='"+txtMerk.getText()+"'";
            java.sql.Connection conn = (Connection)tokoberas.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilkan();
        kosongkan();
    }//GEN-LAST:event_tbEditActionPerformed

    private void tbHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbHapusActionPerformed
        try{
            String sql = "DELETE FROM gudang WHERE kode_beras='"+txtKode.getText()+"'";
            java.sql.Connection conn = (Connection)tokoberas.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilkan();
        kosongkan();
        // TODO add your handling code here:
    }//GEN-LAST:event_tbHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUDANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUDANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUDANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUDANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUDANG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable tabelGudang;
    private javax.swing.JButton tbEdit;
    private javax.swing.JButton tbHapus;
    private javax.swing.JButton tbOut;
    private javax.swing.JButton tbSave;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtMerk;
    private javax.swing.JTextField txtStok;
    // End of variables declaration//GEN-END:variables
}
